#!/usr/bin/env node

// This is a script written to run from your blog
// folder once the app has been deployed.
//
// Just make a folder anywhere and put a credentials.js file
// and a posts/ directory in it. Then you can run this script
// whenever you're cdied in there.

const { AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, url } = require(process.env.PWD + '/credentials.js')
const { exec } = require('child_process')

if(!AWS_SECRET_ACCESS_KEY || !AWS_ACCESS_KEY_ID) {
  console.log('No AWS config included. Add a file called credentials.js to this folder to upload.')
} else {
  exec(`export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"; export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"; aws s3 sync ${process.env.PWD}/posts ${url} --acl public-read`, (e, stdout, stderr) => {
    if(e) {
      console.log('There was an error syncing with the s3')
      console.log(stderr)
      return
    }

    console.log(stdout)
    console.log('Done!')

  })
}

